"""CellScan — Industrial EL Defect Screening Console.

A polished, recruiter-ready demo UI over the CellScan pipeline:
single-image inspection with Grad-CAM, batch screening with CSV export,
a live metrics dashboard fed by reports/metrics.json, and a failure-case
explorer. Every number shown is read from artifacts generated by the
training/evaluation pipeline — nothing is hard-coded.

Run:  streamlit run app/streamlit_app.py
"""
from __future__ import annotations

import io
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import torch
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cellscan.config import DEFAULT  # noqa: E402
from cellscan.data import build_transforms  # noqa: E402
from cellscan.gradcam import GradCAM, overlay  # noqa: E402
from cellscan.model import load_checkpoint  # noqa: E402

CKPT = DEFAULT.models_dir / "cellscan_resnet18.pt"
METRICS = DEFAULT.reports_dir / "metrics.json"
SPLITS = DEFAULT.splits_csv

# ----------------------------------------------------------------------------- 
# Page config + theme
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="CellScan · EL Defect Screening",
    page_icon="🔆",
    layout="wide",
    initial_sidebar_state="expanded",
)

ACCENT = "#F59E0B"       # solar amber
ACCENT_SOFT = "#FBBF24"
GOOD = "#10B981"
BAD = "#EF4444"
WARN = "#F59E0B"
INK = "#E7E5E4"
MUTED = "#A8A29E"
PANEL = "#1C1917"
PANEL2 = "#292524"
EDGE = "#44403C"

st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');

html, body, [class*="css"] {{
    font-family: 'Space Grotesk', -apple-system, sans-serif;
}}
.stApp {{
    background: radial-gradient(1200px 600px at 15% -10%, #292018 0%, #0C0A09 55%) fixed;
}}
section[data-testid="stSidebar"] {{
    background: linear-gradient(180deg, #171412 0%, #0C0A09 100%);
    border-right: 1px solid {EDGE};
}}
h1, h2, h3 {{ color: {INK}; letter-spacing: -0.02em; }}
p, li, span, label {{ color: {INK}; }}

/* hero */
.cs-hero {{
    background: linear-gradient(120deg, rgba(245,158,11,0.14) 0%, rgba(245,158,11,0.03) 55%, transparent 100%);
    border: 1px solid rgba(245,158,11,0.35);
    border-radius: 18px;
    padding: 26px 30px 22px 30px;
    margin-bottom: 6px;
}}
.cs-hero h1 {{
    margin: 0; font-size: 2.1rem; font-weight: 700;
    background: linear-gradient(90deg, #FDE68A, {ACCENT});
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
}}
.cs-hero p {{ color: {MUTED}; margin: 8px 0 0 0; font-size: 0.98rem; }}
.cs-badges {{ margin-top: 14px; }}
.cs-badge {{
    display: inline-block; padding: 4px 12px; margin: 0 8px 6px 0;
    border-radius: 999px; font-size: 0.78rem; font-weight: 600;
    background: rgba(245,158,11,0.12); color: {ACCENT_SOFT};
    border: 1px solid rgba(245,158,11,0.35);
    font-family: 'JetBrains Mono', monospace;
}}

/* metric cards */
.cs-card {{
    background: linear-gradient(160deg, {PANEL2} 0%, {PANEL} 100%);
    border: 1px solid {EDGE}; border-radius: 14px;
    padding: 18px 20px; height: 100%;
}}
.cs-card .k {{ color: {MUTED}; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.08em; }}
.cs-card .v {{ color: {INK}; font-size: 1.9rem; font-weight: 700; font-family: 'JetBrains Mono', monospace; margin-top: 2px; }}
.cs-card .s {{ font-size: 0.8rem; margin-top: 4px; }}

/* verdict panel */
.cs-verdict {{
    border-radius: 16px; padding: 24px; text-align: center;
    border: 2px solid var(--vc); background:
      linear-gradient(160deg, color-mix(in srgb, var(--vc) 16%, transparent),
                              color-mix(in srgb, var(--vc) 5%, transparent));
}}
.cs-verdict .title {{ color: var(--vc); font-size: 1.5rem; font-weight: 700; letter-spacing: 0.04em; }}
.cs-verdict .prob  {{ color: {INK}; font-size: 3rem; font-weight: 700; font-family: 'JetBrains Mono', monospace; line-height: 1.1; }}
.cs-verdict .sub   {{ color: {MUTED}; font-size: 0.82rem; }}

/* confidence bar */
.cs-bar-wrap {{ background: {PANEL2}; border: 1px solid {EDGE}; border-radius: 999px; height: 14px; overflow: hidden; margin: 10px 0 4px 0; }}
.cs-bar-fill {{ height: 100%; border-radius: 999px; transition: width 0.6s ease; }}
.cs-scale {{ display:flex; justify-content:space-between; color:{MUTED}; font-size:0.72rem; font-family:'JetBrains Mono',monospace; }}

/* confusion matrix grid */
.cm-grid {{ display: grid; grid-template-columns: 90px 1fr 1fr; gap: 8px; max-width: 520px; }}
.cm-cell {{ border-radius: 10px; padding: 16px 10px; text-align: center; border: 1px solid {EDGE}; }}
.cm-cell .n {{ font-size: 1.5rem; font-weight: 700; font-family: 'JetBrains Mono', monospace; }}
.cm-cell .t {{ font-size: 0.72rem; color: {MUTED}; }}
.cm-head {{ display:flex; align-items:center; justify-content:center; color:{MUTED}; font-size:0.78rem; }}

div[data-testid="stFileUploader"] {{ border-radius: 14px; }}
button[kind="primary"] {{ background: {ACCENT} !important; color: #1C1300 !important; font-weight: 700 !important; }}
hr {{ border-color: {EDGE}; }}
</style>
""", unsafe_allow_html=True)


# ----------------------------------------------------------------------------- 
# Cached resources
# -----------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading model checkpoint…")
def get_model():
    if not CKPT.exists():
        return None
    return load_checkpoint(CKPT)


@st.cache_data
def get_metrics() -> dict | None:
    if not METRICS.exists():
        return None
    return json.loads(METRICS.read_text())


@st.cache_data
def get_test_split() -> pd.DataFrame | None:
    if not SPLITS.exists():
        return None
    df = pd.read_csv(SPLITS)
    return df[df["split"] == "test"].reset_index(drop=True)


def predict(img: Image.Image, tf, model, temperature: float, cam_alpha: float):
    """Run one image through the model; return prob, gradcam overlay, latency ms."""
    x = tf(img).unsqueeze(0)
    t0 = time.perf_counter()
    cam, logit = GradCAM(model)(x)          # needs gradients — no torch.no_grad here
    latency_ms = (time.perf_counter() - t0) * 1000
    prob = float(torch.sigmoid(torch.tensor(logit / temperature)))
    gray = np.array(img.resize((300, 300)))
    cam_r = np.array(Image.fromarray((cam * 255).astype(np.uint8)).resize((300, 300))) / 255.0
    heat = overlay(gray, cam_r, alpha=cam_alpha)
    return prob, heat, latency_ms


def verdict_block(prob: float, threshold: float, latency_ms: float | None = None):
    defective = prob >= threshold
    color = BAD if defective else GOOD
    label = "DEFECTIVE" if defective else "FUNCTIONAL"
    icon = "⛔" if defective else "✅"
    lat = f'<div class="sub" style="margin-top:6px;">inference {latency_ms:.0f} ms · T-scaled</div>' if latency_ms else ""
    st.markdown(f"""
    <div class="cs-verdict" style="--vc:{color};">
        <div class="title">{icon} {label}</div>
        <div class="prob">{prob:.1%}</div>
        <div class="sub">calibrated defect probability · decision threshold {threshold:.2f}</div>
        {lat}
    </div>
    """, unsafe_allow_html=True)
    # confidence bar
    st.markdown(f"""
    <div class="cs-bar-wrap"><div class="cs-bar-fill" style="width:{prob*100:.1f}%;
         background:linear-gradient(90deg,{GOOD},{WARN} 55%,{BAD});"></div></div>
    <div class="cs-scale"><span>0 · functional</span><span>{threshold:.2f}</span><span>1 · defective</span></div>
    """, unsafe_allow_html=True)


def guidance(prob: float):
    if prob >= 0.9:
        st.error("**High-confidence defect.** Flag module for replacement / detailed EL review.")
    elif prob >= 0.7:
        st.warning("**Probable defect.** Queue for human inspection; check Grad-CAM region.")
    elif prob >= 0.5:
        st.warning("**Borderline.** Signal present but weak — review with a domain expert.")
    elif prob >= 0.3:
        st.info("**Likely functional.** No strong defect evidence; spot-check if critical string.")
    else:
        st.success("**High-confidence functional.** Clear for deployment.")


# ----------------------------------------------------------------------------- 
# Sidebar — model card + live controls
# -----------------------------------------------------------------------------
loaded = get_model()
metrics = get_metrics()

with st.sidebar:
    st.markdown(f"## 🔆 CellScan")
    st.caption("EL Defect Screening Console")
    st.markdown("---")

    ok = lambda b: "🟢" if b else "🔴"
    st.markdown(f"""
**System status**

{ok(loaded is not None)} model checkpoint  
{ok(metrics is not None)} evaluation metrics  
{ok(SPLITS.exists())} test split manifest
""")
    st.markdown("---")

    st.markdown("**Inference controls**")
    threshold = st.slider("Decision threshold", 0.05, 0.95, 0.50, 0.05,
                          help="Probability above which a cell is flagged DEFECTIVE. "
                               "Lower = higher recall (catch more defects), higher = higher precision.")
    cam_alpha = st.slider("Grad-CAM opacity", 0.15, 0.85, 0.45, 0.05)

    st.markdown("---")
    if metrics:
        st.markdown(f"""
**Model card**
- Backbone · ResNet-18 (ImageNet)
- Test AUROC · `{metrics['auroc']:.4f}`
- Test F1 (defect) · `{metrics['f1_defective']:.4f}`
- Temperature · `{metrics['temperature']:.3f}`
- Test set · n = {metrics['n_test']}
""")
    st.markdown("---")
    st.caption("ELPV dataset · CC BY-NC-SA 4.0\n\nResearch / education demo — **not** a certified inspection tool.")


# ----------------------------------------------------------------------------- 
# Hero
# -----------------------------------------------------------------------------
hero_badges = ""
if metrics:
    hero_badges = (
        f'<span class="cs-badge">AUROC {metrics["auroc"]:.4f}</span>'
        f'<span class="cs-badge">F1 {metrics["f1_defective"]:.4f}</span>'
        f'<span class="cs-badge">ECE {metrics["ece_calibrated"]:.3f}</span>'
        f'<span class="cs-badge">ResNet-18 · AMP</span>'
        f'<span class="cs-badge">Grad-CAM</span>'
        f'<span class="cs-badge">Temperature-scaled</span>'
    )
st.markdown(f"""
<div class="cs-hero">
  <h1>CellScan — Solar Cell Defect Detection</h1>
  <p>Explainable electroluminescence screening: calibrated defect probability, visual evidence,
  and an honest test-set report. Every metric on this page is read from pipeline artifacts.</p>
  <div class="cs-badges">{hero_badges}</div>
</div>
""", unsafe_allow_html=True)

if loaded is None:
    st.error(f"No trained checkpoint at `{CKPT}`. Train one first:\n\n"
             "```\npython scripts/prepare_data.py\npython -m cellscan.train\n```")
    st.stop()

model, temperature, ckpt_cfg = loaded
tf = build_transforms(DEFAULT, train=False)

tab_inspect, tab_batch, tab_dash, tab_about = st.tabs(
    ["🔍  Inspect", "🗂️  Batch screening", "📊  Dashboard", "🧠  How it works"]
)

# ----------------------------------------------------------------------------- 
# TAB 1 — single-image inspection
# -----------------------------------------------------------------------------
with tab_inspect:
    left, right = st.columns([2.2, 1])
    with left:
        up = st.file_uploader("Upload an EL cell image (grayscale PNG/JPG)",
                              type=["png", "jpg", "jpeg"])
    with right:
        st.markdown("**Or try a real test-set cell**")
        test_df = get_test_split()
        sample_clicked = st.button("🎲 Random test sample",
                                   disabled=test_df is None,
                                   use_container_width=True)
        if test_df is None:
            st.caption("`data/splits.csv` not found — run `scripts/prepare_data.py`.")

    img: Image.Image | None = None
    truth_row = None

    if sample_clicked and test_df is not None:
        row = test_df.sample(1).iloc[0]
        p = DEFAULT.data_dir / row["path"]
        if p.exists():
            st.session_state["sample"] = {"path": str(p), "proba": float(row["proba"]),
                                          "label": int(row["label"]), "cell_type": row["cell_type"]}
        else:
            st.warning(f"Image file missing on disk: `{p}` — run `scripts/prepare_data.py` to download ELPV.")

    if up is not None:
        img = Image.open(up).convert("L")
        st.session_state.pop("sample", None)
    elif "sample" in st.session_state:
        truth_row = st.session_state["sample"]
        img = Image.open(truth_row["path"]).convert("L")

    if img is None:
        st.info("Upload an image or draw a random test-set cell to begin.")
    else:
        prob, heat, latency_ms = predict(img, tf, model, temperature, cam_alpha)

        c1, c2, c3 = st.columns([1, 1, 1.25], gap="large")
        with c1:
            st.markdown("##### Input")
            st.image(img, use_container_width=True)
        with c2:
            st.markdown("##### Grad-CAM evidence")
            st.image(heat, use_container_width=True,
                     caption="regions driving the defect score")
        with c3:
            st.markdown("##### Verdict")
            verdict_block(prob, threshold, latency_ms)
            st.markdown("")
            guidance(prob)

        # model vs expert (only for test samples — ground truth is known)
        if truth_row is not None:
            st.markdown("---")
            st.markdown("##### Model vs. expert label")
            e1, e2, e3 = st.columns(3)
            e1.markdown(f'<div class="cs-card"><div class="k">Expert defect probability</div>'
                        f'<div class="v">{truth_row["proba"]:.2f}</div>'
                        f'<div class="s">original ELPV annotation</div></div>', unsafe_allow_html=True)
            e2.markdown(f'<div class="cs-card"><div class="k">Binarized ground truth</div>'
                        f'<div class="v">{"DEFECT" if truth_row["label"] else "OK"}</div>'
                        f'<div class="s">threshold ≥ 0.5</div></div>', unsafe_allow_html=True)
            agree = (prob >= threshold) == bool(truth_row["label"])
            e3.markdown(f'<div class="cs-card"><div class="k">Model agrees?</div>'
                        f'<div class="v" style="color:{GOOD if agree else BAD};">{"YES" if agree else "NO"}</div>'
                        f'<div class="s">{truth_row["cell_type"]} cell</div></div>', unsafe_allow_html=True)

        # downloadable per-image report
        report = {
            "calibrated_defect_probability": round(prob, 4),
            "decision_threshold": threshold,
            "verdict": "DEFECTIVE" if prob >= threshold else "FUNCTIONAL",
            "temperature": round(float(temperature), 4),
            "inference_ms": round(latency_ms, 1),
            "model": "cellscan_resnet18",
        }
        if truth_row is not None:
            report["ground_truth"] = truth_row
        st.download_button("⬇️ Download prediction report (JSON)",
                           data=json.dumps(report, indent=2),
                           file_name="cellscan_prediction.json",
                           mime="application/json")

# ----------------------------------------------------------------------------- 
# TAB 2 — batch screening with CSV export
# -----------------------------------------------------------------------------
with tab_batch:
    st.markdown("#### Screen a batch of cells")
    st.caption("Upload multiple EL images — get a sortable results table and a CSV you can "
               "hand to a QA workflow. Uses the same calibrated model as single inspection.")

    files = st.file_uploader("Upload images", type=["png", "jpg", "jpeg"],
                             accept_multiple_files=True, key="batch")
    if files:
        rows, t0 = [], time.perf_counter()
        prog = st.progress(0.0, text="Screening…")
        for i, f in enumerate(files):
            im = Image.open(f).convert("L")
            x = tf(im).unsqueeze(0)
            with torch.no_grad():                       # plain forward — no CAM needed
                logit = float(model(x).squeeze())
            p = float(torch.sigmoid(torch.tensor(logit / temperature)))
            rows.append({"file": f.name,
                         "defect_probability": round(p, 4),
                         "verdict": "DEFECTIVE" if p >= threshold else "FUNCTIONAL"})
            prog.progress((i + 1) / len(files), text=f"Screening… {i+1}/{len(files)}")
        total_s = time.perf_counter() - t0
        prog.empty()

        df = pd.DataFrame(rows).sort_values("defect_probability", ascending=False)
        n_def = int((df["verdict"] == "DEFECTIVE").sum())

        m1, m2, m3 = st.columns(3)
        m1.markdown(f'<div class="cs-card"><div class="k">Cells screened</div><div class="v">{len(df)}</div></div>', unsafe_allow_html=True)
        m2.markdown(f'<div class="cs-card"><div class="k">Flagged defective</div><div class="v" style="color:{BAD};">{n_def}</div><div class="s">at threshold {threshold:.2f}</div></div>', unsafe_allow_html=True)
        m3.markdown(f'<div class="cs-card"><div class="k">Throughput</div><div class="v">{len(df)/max(total_s,1e-6):.1f}/s</div><div class="s">{total_s*1000/len(df):.0f} ms per cell</div></div>', unsafe_allow_html=True)

        st.markdown("")
        st.dataframe(
            df, use_container_width=True, hide_index=True,
            column_config={"defect_probability": st.column_config.ProgressColumn(
                "defect probability", min_value=0.0, max_value=1.0, format="%.3f")},
        )
        st.download_button("⬇️ Export results (CSV)", df.to_csv(index=False),
                           file_name="cellscan_batch_results.csv", mime="text/csv")
    else:
        st.info("Drop several images above to run a screening batch.")

# ----------------------------------------------------------------------------- 
# TAB 3 — dashboard from reports/metrics.json
# -----------------------------------------------------------------------------
with tab_dash:
    if metrics is None:
        st.error("`reports/metrics.json` not found. Run `python -m cellscan.evaluate`.")
    else:
        st.markdown("#### Held-out test set · n = " + str(metrics["n_test"]))
        g1, g2, g3, g4, g5 = st.columns(5)
        cards = [
            ("AUROC", f"{metrics['auroc']:.4f}", "ranking quality", ACCENT_SOFT),
            ("Avg precision", f"{metrics['average_precision']:.4f}", "PR-curve area", ACCENT_SOFT),
            ("F1 · defect", f"{metrics['f1_defective']:.4f}", "at 0.5 threshold", INK),
            ("Precision / Recall", f"{metrics['precision_defective']:.2f}/{metrics['recall_defective']:.2f}", "defect class", INK),
            ("ECE cal.", f"{metrics['ece_calibrated']:.4f}", f"T = {metrics['temperature']:.2f}", GOOD),
        ]
        for col, (k, v, s, c) in zip([g1, g2, g3, g4, g5], cards):
            col.markdown(f'<div class="cs-card"><div class="k">{k}</div>'
                         f'<div class="v" style="color:{c};">{v}</div>'
                         f'<div class="s" style="color:{MUTED};">{s}</div></div>',
                         unsafe_allow_html=True)

        st.markdown("---")
        cA, cB = st.columns([1, 1], gap="large")

        with cA:
            st.markdown("##### Confusion matrix (threshold 0.5)")
            (tn, fp), (fn, tp) = metrics["confusion_matrix"]
            st.markdown(f"""
<div class="cm-grid">
  <div></div><div class="cm-head">pred OK</div><div class="cm-head">pred DEFECT</div>
  <div class="cm-head">true OK</div>
  <div class="cm-cell" style="background:rgba(16,185,129,0.12);"><div class="n" style="color:{GOOD};">{tn}</div><div class="t">true neg</div></div>
  <div class="cm-cell" style="background:rgba(239,68,68,0.10);"><div class="n" style="color:{BAD};">{fp}</div><div class="t">false alarm</div></div>
  <div class="cm-head">true DEFECT</div>
  <div class="cm-cell" style="background:rgba(239,68,68,0.10);"><div class="n" style="color:{BAD};">{fn}</div><div class="t">missed defect</div></div>
  <div class="cm-cell" style="background:rgba(16,185,129,0.12);"><div class="n" style="color:{GOOD};">{tp}</div><div class="t">true pos</div></div>
</div>""", unsafe_allow_html=True)

            st.markdown("##### By cell type")
            st.markdown(f"""
| | AUROC | F1 |
|---|---|---|
| **Mono** | `{metrics['auroc_mono']:.4f}` | `{metrics['f1_mono']:.4f}` |
| **Poly** | `{metrics['auroc_poly']:.4f}` | `{metrics['f1_poly']:.4f}` |
""")
            st.caption("Splits are stratified jointly on label × cell type, so this gap is a "
                       "real texture-difficulty effect, not a sampling artifact.")

        with cB:
            rel = DEFAULT.reports_dir / "reliability_diagram.png"
            cm_png = DEFAULT.reports_dir / "confusion_matrix.png"
            if rel.exists():
                st.markdown("##### Calibration (reliability diagram)")
                st.image(str(rel), use_container_width=True)
            if cm_png.exists():
                with st.expander("Matplotlib confusion matrix (from evaluate.py)"):
                    st.image(str(cm_png), use_container_width=True)

        # failure explorer
        fails = metrics.get("failure_cases", [])
        if fails:
            st.markdown("---")
            st.markdown("##### Hardest mistakes — failure explorer")
            st.caption("Most confident errors on the test set. Several are cells the ELPV experts "
                       "themselves marked as ambiguous (raw probability ⅓ or ⅔) — the model is "
                       "confidently flagging genuinely borderline hardware.")
            cols = st.columns(4)
            for i, fc in enumerate(fails[:8]):
                p = ROOT / fc["image"]
                with cols[i % 4]:
                    if p.exists():
                        st.image(str(p), use_container_width=True)
                    truth = "DEFECT" if fc["true_label"] else "OK"
                    st.markdown(
                        f"<div style='font-size:0.78rem;color:{MUTED};font-family:JetBrains Mono,monospace;'>"
                        f"true <b style='color:{INK};'>{truth}</b> · raw {fc['raw_defect_proba_label']:.2f}<br>"
                        f"pred <b style='color:{BAD if (fc['pred_prob_defect']>=0.5)!=bool(fc['true_label']) else GOOD};'>"
                        f"{fc['pred_prob_defect']:.3f}</b> · {fc['cell_type']}</div>",
                        unsafe_allow_html=True)

# ----------------------------------------------------------------------------- 
# TAB 4 — how it works
# -----------------------------------------------------------------------------
with tab_about:
    c1, c2 = st.columns([1.2, 1], gap="large")
    with c1:
        st.markdown("""
#### Pipeline

```
ELPV dataset (2,624 EL images, 44 modules)
        │  scripts/prepare_data.py
        ▼
seeded splits · stratified on label × cell type   →  data/splits.csv
        │  python -m cellscan.train
        ▼
ResNet-18 (ImageNet) · AMP · class-weighted BCE
best-val-AUROC checkpoint + temperature T fitted on val
        │  python -m cellscan.evaluate
        ▼
reports/metrics.json · plots · failure cases   ←  ONLY source of numbers
        │  streamlit run app/streamlit_app.py
        ▼
this console: Grad-CAM inspection · batch screening · dashboard
```

#### Design decisions worth defending

- **Joint stratification (label × cell type).** Mono and poly cells have very
  different texture; without it the test set silently skews and every number lies.
- **Flips-only augmentation.** Rotations/crops create border artifacts that look
  exactly like the cracks being detected.
- **Temperature scaling.** Accuracy metrics are unchanged; the displayed
  probability becomes trustworthy for triage decisions.
- **Grad-CAM from the paper (~50 lines).** No third-party CAM dependency to drift.
- **Metrics discipline.** If a number is not in `reports/metrics.json`,
  it does not appear in the README or this app.
""")
    with c2:
        st.markdown("""
#### Reproduce everything

```bash
git clone https://github.com/ritikgehlot/cellscan
cd cellscan
pip install -r requirements.txt
python scripts/run_full_pipeline.py
streamlit run app/streamlit_app.py
```

~15 min end-to-end on an RTX 4060 (8 GB, AMP).

#### Limitations

- 1-day MVP: single architecture, no HPO, no ensembling
- One dataset, 44 modules — no field-generalization claim
- Binary label discards ⅓ / ⅔ ambiguity
- Grad-CAM localizes evidence, not defect type

#### References

- Deitsch et al., *Solar Energy* 185 (2019) — ELPV benchmark
- Buerhop-Lutz et al., EU PVSEC (2018) — dataset
- Selvaraju et al., ICCV (2017) — Grad-CAM
- Guo et al., ICML (2017) — temperature scaling
""")

st.markdown("---")
st.markdown(f"<div style='text-align:center;color:{MUTED};font-size:0.8rem;'>"
            "CellScan · ELPV (CC BY-NC-SA 4.0) · research & education demo · "
            "built for reproducibility — every number on this page comes from pipeline artifacts"
            "</div>", unsafe_allow_html=True)
